name: questrip
description: SW Team [12] LevelUp

version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_facebook_login: ^2.0.0
  flutter_inappbrowser: ^1.1.1
  flutter_kakao_login: ^0.3.0
  flutter_svg: ^0.12.4
  fluttertoast: ^3.0.3
  google_maps_flutter: ^0.5.7
  location: ^2.3.5
  photo_view: ^0.3.1
  image_picker: ^0.6.0+3
  image_gallery_saver: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/drawable/
    - res/values/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
